### ISSUE TITLE
Add `exec` param to `target` to run a process

### ISSUE THREAD

**Issue by dherbst** [streamingrat/ratproxy#4]
In the `target` section, add `exec` with a line to run something and capture the logs.  The working directory should be relative to the `ratproxy.yaml` file, with a name `exec-working-dir` The logs can be seen in the `admin` listener.

Expected configuration:

```yaml
listen: 0.0.0.0:1414
targets:
  - name: npm-run-vue-app
    target: http://localhost:5173
    path: /vue/
    exec: npm run dev
    exec-working-dir: ./web/vue-app
  - name: other-target
```
